### ISSUE TITLE
Dec 2nd week 2 updates

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#15]
Lost this morning to needing to review proofs for a journal, but pulled together first two readings for numpy (class 2, week 2). Significant upfront overhead on intro, next up is integrating the rest of the R tutorials into numpy. Will work on that tomorrow!

**Comment by nickeubank** [comment]
I already hate it and know how I want to re-organize it. Please don't judge me.

**Comment by kylebradbury** [comment]
This is a judgement free zone! That being said, the core content looks good. I generally like an iterative approach - get the minimum viable product and feedback before we get to deep. Thanks, Nick!

**Comment by nickeubank** [comment]
Awesome, thanks. OK, pushed a huge block of updates. Think it's sane now, though the `30_manipulating_vectors` might need to engage with views and copies... really want to put off, but can't tell if I can.
