### ISSUE TITLE
Course 2 week 4 updates

### ISSUE THREAD

**Issue by kylebradbury** [nickeubank/mids_coursera#16]
I've tried to cover each of the four sections we described for week 4: summarization of arrays, vectorization (from which I kept most of your content and added some potential additions that need to be blended in), and random number generation. I'm thinking some reordering will be needed, and I'll be working on merging/blending in the morning as well.

Similar to what I believe you were implying about the sections you mentioned - let's perhaps treat these as versions 0.1.

**Comment by nickeubank** [comment]
Love it! 

One question: there's a lot of `.format()` stuff in there -- its that legacy from me / do you know f-strings? I feel like they're really taking over, and we might want to do all string formatting with them. 

(e.g. 10_vectorization_performance_understanding.ipynb: `print('Sum of squares = {:0.4f}'.format(sum_of_squares_vectorized))`

**Comment by nickeubank** [comment]
I hope you don't mind, but I moved your stuff up to the `/class_2` folder from inside `practicaldatascience_materials` so we can differentiate coursera-specific material from older stuff from my class

**Comment by nickeubank** [comment]
*great* visualization: 

![image](https://user-images.githubusercontent.com/9683693/144669022-ed63219e-fc14-4d57-97cb-3b2656266f35.png)
