### ISSUE TITLE
print statements in notebooks

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#19]
Style question: I've noticed that you tend to use `print()` even when printing will be done implicitly in a jupyter notebook because the thing you are printing is the last output in a cell:

![image](https://user-images.githubusercontent.com/9683693/146387728-e2b4bd1b-fcc4-46dc-b8f9-670c56624d87.png)

My general inclination is to not use `print()` in these situations because it just seems to interfere with the parsimonious presentation of the code that were focused on. There are still cases where it makes sense -- I'm fine with it in situations like this:

![image](https://user-images.githubusercontent.com/9683693/146387893-52f97926-1cdc-48b6-91b7-43934df0d8af.png)

But how would you feel if we avoided using `print()` when trying to print out the last output of a cell?

**Comment by kylebradbury** [comment]
Fine with me - I don't have strong feelings either way. Let's make the default be not use print when there are not multiple outputs being shown in one cell. Will add to the formatting checklist.

We may just want to mention that this output will only be present in notebook environments, not from `.py` files.
