### ISSUE TITLE
f-strings v. .format()

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#20]
There's a lot of .format() stuff in your week 4 stuff -- its that legacy from me / do you know f-strings? I feel like they're really taking over, and we might want to do all string formatting with them.

e.g. 10_vectorization_performance_understanding.ipynb: 

```python
print('Sum of squares = {:0.4f}'.format(sum_of_squares_vectorized))
```

I think the more popular way to do this now is:

```python
print(f'Sum of squares = {sum_of_squares_vectorized:0.4f}')
```

**Comment by kylebradbury** [comment]
I like streamlining notation, so that sounds good! I'll add it to the formatting checklist!
