### ISSUE TITLE
black formatting

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#22]
I just pathologically format all of my stuff with black these days -- might I suggest we do that throughout? 

You can do it automatically on save for .py files, and with a keyboard shortcut for notebooks. Let me know if it would be helpful for me to show you how to set that up!

(I went through and formatted your week 4 stuff, hope that's ok)

**Comment by kylebradbury** [comment]
Works for me. If you can send me a long or show me how to do it, happy to. Since I made tons of edits throughout, I'll need to reapply Black throughout.

**Comment by nickeubank** [comment]
When you have a notebook open in VS code and right click on a code cell, you should see an option to format cell and an option to format notebook. It's possible you have to have already configured blank as your default python formatter in the settings for the python package, but I'm not sure...

**Comment by nickeubank** [comment]
![image](https://user-images.githubusercontent.com/9683693/148837410-f535ce0c-626c-4b42-bb2b-22c5f54ebc26.png)

**Comment by kylebradbury** [comment]
Thanks again for the instructions here. I've been using black on the sections now, and I found I can use it most, but not all of the time. For example, I have [an exercise](https://github.com/nickeubank/mids_coursera/blob/main/class_2/week_4/05_EX_summarizing_arrays.ipynb) that contains a vector of 500 values (allowing the student to see the data they're working with). Black makes that into a 500-line array. I know it's an exception (and one that could be moved to a file), but I'll plan to exclude a couple of files from black formatting and may just apply autopep8 there which should look quite similar in the end.

**Comment by nickeubank** [comment]
Sounds great! Those type of exceptions obviously make sense! I'm not a crazy zealot about it, I just think it makes sense to use it most of the time for consistency.
