### ISSUE TITLE
Figure for intro to vectors

### ISSUE THREAD

**Issue by kylebradbury** [nickeubank/mids_coursera#24]
Drafted [this figure](https://raw.githubusercontent.com/nickeubank/mids_coursera/main/figure_prep/scalar-vector-matrix.png) for course 2, week 2, item 20, intro to vectors. I figure we could refer to this for indexing, too. Let me know if this is in line with your thinking and, as always, happy to edit.

**Comment by nickeubank** [comment]
I'm hiding the `[]` indexing tricks till week 3, 30 and then 40, so I think maybe we should put it in `week_3/40_nd_arrays.ipynb`?

**Comment by kylebradbury** [comment]
Sure - would it be helpful to have two versions - one without for early on, then on with for week 3? Happy to make them.

**Comment by nickeubank** [comment]
Absolutely!

**Comment by kylebradbury** [comment]
Great - I created two new versions. [One without indices](https://raw.githubusercontent.com/nickeubank/mids_coursera/main/figure_prep/scalar-vector-matrix-no-indices.png) and one [without indices or the 4th dimension](https://raw.githubusercontent.com/nickeubank/mids_coursera/main/figure_prep/scalar-vector-matrix-up-to-3d.png). Let me know if any other versions would be helpful.

**Comment by nickeubank** [comment]
I think the later will be ideal -- 4D is a little mind-bending for the first week. :) 

How do you make these? Some vector-art software?

**Comment by kylebradbury** [comment]
Sounds great - we can remove the 4th dimension for the one with indices if clearer as well.

Actually, I make them in powerpoint and save as high-res PNGs or JPGs. I have made similar stuff in [Inkscape](https://inkscape.org/) when I wanted EPS files, but PowerPoint and a little patience usually does the trick for me :)

**Comment by nickeubank** [comment]
Damn -- I was hoping you had a special trick, and that was the reason you were so much better this! I hate it when the answer is "practice and hard work".
