### ISSUE TITLE
Decoding common errors

### ISSUE THREAD

**Issue by kylebradbury** [nickeubank/mids_coursera#25]
I really liked the spots in the sections you drafted when you showed common errors. Oh look! I tried to add a vector with two elements to a vector with 3 and I broke it. Would it be worth having an item on how to decode common errors? I feel like there's a lot of pattern recognition that needs to be learned to debug successfully; perhaps we can assist in accelerating that learning process...

**Comment by nickeubank** [comment]
Seems like this is just a thought for the future, not something we need to deal with concretely?
