### ISSUE TITLE
DLI meeting notes (Jan 7, 2022)

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#30]
Original Memo: https://docs.google.com/document/d/14aXtD3xZChzuaBo_iqHIHJwnsd6B94oaBDsFMAqX7Yo/edit

- Split readings (~400 lines)
- Add toy exercises at the end of readings
- Not all exercises need be graded
- Add honor exercises

Exercises:

- Split into (a) ungraded, (b) graded, and (c) honors

Videos: 

- Live coding (with errors!)

**Comment by kylebradbury** [comment]
The above matched my notes, too. One addition:
- Contextualizing where/how each skill will be applied in practice in data science (potentially through a short intro video for each topic)

DLI folder with all associated information: https://drive.google.com/drive/folders/1jYUAfl2xydJ_YnEIzjKLx_bp8o6_EtWM
