### ISSUE TITLE
Week 2 Handoff

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#32]
OK, here you are!

At this point I think:

- Readings `10_` through `35_` are done, including the "exercises we suggest students just do at the bottom of the reading."
- Readings `30_` through `45_` are done, **except** the "exercises we suggest students just do at the bottom of the reading" which aren't there yet. But the bigger to-be-graded `45_EX_vectors_2` is, I think, done. At the moment it doesn't really sum up to a deep insight about inequality in a way that I would like, so if I can think of some substantive take away I can get at with small manipulations I may still make those, but in terms of calibrating difficulty and substance and length I think the exercise is what I wanted it to be.

I also think it will make sense for you to read through the instructional material if you can find time -- I think there can be lots of these little things where a topic is introduced and covered by one of us and we don't want to make it redundant for the other (e.g. a quick introduction to `time.time()` in [why numpy](https://github.com/nickeubank/mids_coursera/blob/main/class_2/week_2/10_why_numpy.ipynb) you might otherwise not know is there. 

(Plus would really like your input on how concepts are being introduced!)

**Comment by kylebradbury** [comment]
Hi Nick - I've had a chance to go through all of the materials (with attention to the points you mentioned above). I left comments in ReviewNB as well for most notebooks (please let me know if you can't see them and I'd also be happy to send links). Overall, I found the presentation extremely clear with plenty of scaffolding along the way. I thought the pace was right as was the overall focus of the topics. I did note some areas of redundancy between Week 4 and the materials covered, so we may want to discuss that (some of that may be useful for foreshadowing and building bridges to topics, though).

I REALLY liked the final exercise that you added - I think it's a nice mini project that gets students legitimately thinking like data scientists. I added a few comments for increasing clarity, but the idea seems very well constructed. Given the depth and cohesion of that final exercise, I think I should add a similarly deep exercise to the end of week 4 - each week should end with students using their tools to think like data scientists. I'll work on that for the final edits tonight before we hand off to the DLI folks.

Really great work here, Nick!

**Comment by nickeubank** [comment]
SUPER helpful, thanks Kyle! Think I've made all the suggested edits as well as integrated your graphics! As I noted in my response to your comment, I concur that there is a little bit of redundancy around discussion of vectorized code, but I think students who are used to writing in loops well struggle if we don't acknowledge that were asking them to do something in a very different way. I think my hope is that a little upfront acknowledgment will help address that *and* hopefully prime them for our later and more in-depth discussion. I hope that seems OK?

Thanks again for all the help!
