### ISSUE TITLE
Week 4 Handoff

### ISSUE THREAD

**Issue by kylebradbury** [nickeubank/mids_coursera#33]
Ready for your review!

A few notes:
- For the exercises, I included anticipated "solutions" for most of them to give a sense of what's involved
- As I'm looking at the exercises, I think they're OK, but I'm just worried they're too simple. When I try to add in greater complexity, however, I quickly veer into the territory of material we haven't yet covered. Would love your thoughts on the level of difficulty and calibrating whether or not we're really testing them thoroughly enough on the materials.
- Of course would love your feedback on the materials as well, time-allowing. The packages section feels a bit out of place, here, but not sure where else it would go given the other topics we need to cover.

Thanks in advance for your input!

**Comment by nickeubank** [comment]
I'm adding some comments on reviewNB -- basically a tool that allows for standard github code commenting but on notebooks. Let me know if you get notifications from them?

https://app.reviewnb.com/nickeubank/mids_coursera/blob/main/class_2%2Fweek_4%2F00_summarizing_arrays.ipynb/file

**Comment by nickeubank** [comment]
https://app.reviewnb.com/nickeubank/mids_coursera/blob/main/class_2%2Fweek_4%2F05_EX_summarizing_arrays.ipynb/file

**Comment by nickeubank** [comment]
Sorry, note sure if you can find these easily if I don't link each notebook -- tell me if you want me to stop! https://app.reviewnb.com/nickeubank/mids_coursera/blob/main/class_2/week_4/10_speed_and_ease%20of%20use.ipynb/

**Comment by kylebradbury** [comment]
This is so cool! I wasn't familiar with this tool and REALLY like it. I think I can see them all navigating to the main menu. And this is a MUCH more efficient way to add comments. Do you know what happens to the comments when we make new commits that make changes?

**Comment by nickeubank** [comment]
not sure... the easiest way is to comment on PRs (like a regular code review). I think these are anchored to the current commit, but... we'll see!

**Comment by nickeubank** [comment]
Great work again Kyle! I think you're right that we can probably develop the last exercise a little bit more, and reading it in context I do think that reading `10` on performance is a little underdeveloped (I say acknowledging fully that I am the person who wrote the first draft 🤣). If it's helpful, I did start to talk about [memory here](https://github.com/nickeubank/mids_coursera/blob/main/practicaldatascience_materials/40_wide_numpy_is_fast_memory_explanation.ipynb), and sounds like Drew and Genevieve have *touched* on heap allocation previously. 

In in the interest of not making the earlier discussion  of vectorization repetitive, I was thinking it might make sense to also introduce some of the np tools for [vectorization of custom functions](https://numpy.org/doc/stable/reference/routines.functional.html)?

**Comment by kylebradbury** [comment]
Very helpful - thanks for the detailed comments! I think it helped to improve the content quite a bit. I added a new exercise to the end of Week 4 - please take a glance when you have a chance if you think what we're evaluating there will make sense in Exercise 2 (filtering/querying data with numpy operations). I could tweak to add more real-world meaning to the exercise (e.g. add in real-world data, make the filtering/querying nominally connected to a real question), but figured I'd get your thoughts on whether the exercise makes sense as a mini "capstone" for course 2.

I'll take a look at D&G's material once they point us in the right direction and I can do some reworking of reading `10` based on what they share. 

The vectorization of custom functions is interesting - admittedly, I've never used it before, but I like the idea of it. It seems to be beneficial for functions that are not vector-aware (for example if the input and output is a float). Have you used any of those before and experienced a notable performance boost? I'm also realizing that "vectorization" has a growing presence in the NLP community, so it may be worthwhile to mention that vectorization may have other meanings in other corners of the data science community.

**Comment by nickeubank** [comment]
> The vectorization of custom functions is interesting - admittedly, I've never used it before, but I like the idea of it. It seems to be beneficial for functions that are not vector-aware (for example if the input and output is a float). Have you used any of those before and experienced a notable performance boost? I'm also realizing that "vectorization" has a growing presence in the NLP community, so it may be worthwhile to mention that vectorization may have other meanings in other corners of the data science community.

I've used [apply()](https://www.datacamp.com/community/tutorials/pandas-apply) and `.map()` in pandas a lot, which is the pandas analogue. The performance is often substantially better. It's also just the way to write code in a vectorized *style* with custom functions, which I think is also just a useful tool. 

I know VERY little about NLP world, I'm afraid!
