### ISSUE TITLE
Add some conceptual quiz questions 

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#42]
apropos suggestion of genevieve

**Comment by kylebradbury** [comment]
I piloted adding quiz questions to the week 4 quiz and things get a bit messy (since some of the questions have analogs in the corresponding lab exercises and others do not). @mvhudson-duke - any thoughts on whether we would be overly confusing to the learners?

**Comment by kylebradbury** [comment]
We can return to this based on user feedback if learners could use additional checkpoints for evaluating understanding beyond what was already added.
