### ISSUE TITLE
Review of pandas graphics

### ISSUE THREAD

**Issue by kylebradbury** [nickeubank/mids_coursera#48]
Graphic 1
![image](https://user-images.githubusercontent.com/4689093/174355406-57fb7634-2a57-4aaf-8fcf-658526bce746.png)

Graphic 2
![image](https://user-images.githubusercontent.com/4689093/174355473-4a9ad9af-cfd2-4860-80bc-9b5f00469336.png)

Graphic 3
![image](https://user-images.githubusercontent.com/4689093/174355536-6ca1be60-e17b-4bfa-8e1b-49a57fd39a31.png)

Graphic 4
![image](https://user-images.githubusercontent.com/4689093/174355582-24b89b4d-78bb-463b-9f6c-8c44c5910f3f.png)

Graphic 5
![image](https://user-images.githubusercontent.com/4689093/174355625-b353320f-fdde-4ee6-b22d-0728d2af4d6b.png)

Graphic 6
![image](https://user-images.githubusercontent.com/4689093/174355664-e64f2456-0af2-4df1-9745-fcee6b5f6282.png)

Graphic 7
![image](https://user-images.githubusercontent.com/4689093/174355723-c6ef49dc-4736-4f15-9966-54a54cfafa40.png)

(idea from figure 6 here: [https://www.textbook.ds100.org/ch/06/pandas_aggregating.html](https://www.textbook.ds100.org/ch/06/pandas_aggregating.html))

Graphic 8
![image](https://user-images.githubusercontent.com/4689093/174355851-dd0cf5c1-cc1d-4f75-85d5-af729887e213.png)

(based off of [https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf))

**Comment by nickeubank** [comment]
![image](https://user-images.githubusercontent.com/9683693/174355392-ee64f3fa-a94f-443a-8c99-d36c91b7bdcb.png)

oops that didn't land. Maybe windows doesn't cut paste as nicely?

**Comment by kylebradbury** [comment]
Oops - tried to fix - can you see them now?

**Comment by nickeubank** [comment]
Perfect thanks!

**Comment by kylebradbury** [comment]
- I assume that the spellcheck squiggly lines are all an artifact of screenshots and won't be in the final?
  - Correct!
- You use the terms "implicit index" and "explicit index"—as you will find in the materials I wrote, I prefer to use the terms "row numbers" and "index labels". How do you feel about that?
  - I like where you're heading and will change those (@kylebradbury) - since both are directly related to index would "row index" and "index labels" be even clearer @nickeubank?
- I love the use of a diverse set of names!
  - Really glad you noticed - I looked online for an international name generator for that one!
- Because we are using black to format most of our code, all of our code examples end up with using double quotes for all strings. It is a small difference but it might feel a little bit more consistent for students if they see the same formatting here.
  - Happy to make that change @kylebradbury 
- In the first image, since > is a valid operator, I feel like students might get a little bit concerned about >>... maybe we could put in an arrow?
  - Will do! @kylebradbury 
- For graphic 5 on concatenation, maybe add a note making clear that axis=0 is implicit / the default behavior, but could be specified explicitly if you wanted. Just a way to make a little bit more clear that concatenating in the two different ways only differs by the value being passed to the keyword (where in one case it is the default)? Unless that's too much... That could also be in the text around it.
  - I think its worth noting this - let me play with it and see if I can find a way to get this into the graphic and if not, will adjust the text. I'll push these images integrated into the narrative @kylebradbury

(FYI - I'm using the "@" symbol to call out those areas I want to make edits on based on this feedback. I mentioned you on ones where I put a question in the reply for you.)

**Comment by nickeubank** [comment]
> I like where you're heading and will change those (@kylebradbury) - since both are directly related to index would "row index" and "index labels" be even clearer @nickeubank?

I think my concern is that the `pd.Index` object (the only place the term "index" is explicitly invoked in pandas) only relates to what I refer to as index labels. I worry that including the word "index" in both of those terms may make it harder remember which concept relates to the `pd.Index` objects that we unfortunately run into all the time. (even the `i` in `.iloc` ostensibly is short for "integer").

**Comment by kylebradbury** [comment]
@kylebradbury - adjust the language on index to match Nick's
