### ISSUE TITLE
Added histograms and motivating example

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#49]
You wanna take a look and let me know what you think? You can see the diff and comment here: https://app.reviewnb.com/nickeubank/mids_coursera/commit/01858a48e2421b3a656cb4ed5e89636c2b3a7ad5/

(Sorry should have done PR not just commit, but think still works)

#47 for week 2; still gotta think about week 3.

**Comment by nickeubank** [comment]
Will put into coursera after you've commented / we're happy with it. 

(@mvhudson-duke also happy to have your input here if you have any).

**Comment by nickeubank** [comment]
Sorry, just to flag I renamed `22_math_with_vectors.ipynb` to `21_math_with_vectors.ipynb` and that diff treats that as a deleted file and a full new one. You can ignore both in that.

**Comment by kylebradbury** [comment]
I really like adding the histograms - I think it makes this section even clearer!

Two additional suggestions:
1. What if we added up the very top after "...they're not" something like, "We'll use this to calculate what the highest levels of income in the United States are today" or something like that
2. For the histograms, while it would make the plotting code a bit longer, what do you think about adding in axes labels? I like the idea that we practice good plotting practices throughout (although I do like the simplicity of having only the single parameter in the function, so I'm torn).
3. What may be hard for the students is that the higher income values look to be exactly zero (even though we know they are not). Is it worth "zooming" in a subsequent plot to show that there are some large values there?

**Comment by nickeubank** [comment]
Number two and number three are pretty closely related I think—it's all about how deep to go at this point. Let me take a shot at adding a little bit more content and then we can take a look at it after. Im a pretty firm believer that the hardest part of teaching is not the provision of instructional content but rather the understanding of what you can hold back so that students know what to prioritize, but at the same time I agree there's something lacking in the current presentation.

**Comment by nickeubank** [comment]
@kylebradbury Can't quite track down what you meant in suggestion 1 above, but addressed the later ones I think. 

Basically, I decided to not try to basically not modify the behavior of matplotlib at all—the only way to get it to behave in a sane manner would be to start with defining an axes object, then running `plt.hist()` with the ax object passed to it, and explaining in even a general sense what's going on there felt like too much. Similarly, creating the histogram with numpy first (e.g. with `np.histogram`) would then require using the [plt.stairs](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.stairs.html#matplotlib.pyplot.stairs) function, which has all the same oddities.

So instead I tried to expose the substantive points you wanted emphasized by subsetting the vector. That is *also* something that the students have not been exposed to at that point, but it's something that they are going to be exposed to in three readings, so felt a lot more coherent.

You can find the pull request of the changes here: https://app.reviewnb.com/nickeubank/mids_coursera/pull/50/
