### ISSUE TITLE
Course 5: This a good idea?

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#54]
I'm feeling dubious about Course 5. I think we might need to re-evaluate some of the ambitions in there—yes, we have a lot of stuff to go in there "done", but as I think I'm being reminded (and I imagine you're finding with my materials) this is far from being as easy as "drag and drop the stuff I drop for IDS 720 into coursera". Might wanna talk about plans for Course 5 Friday/Monday.

**Comment by kylebradbury** [comment]
Thanks, Nick. We've discussed this and decided to redesign Course 5
