### ISSUE TITLE
update matrix / array image?

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#57]
Thoughts on changing labels on bottom to this?

![image](https://user-images.githubusercontent.com/9683693/184645918-333331a8-3bcb-4d0c-9af3-506a68c9441e.png)

Trying to emphasize they're *all* arrays, but some have special names

**Comment by nickeubank** [comment]
And update on Coursera

**Comment by nickeubank** [comment]
Looks like this is fixed. Reopen if not.

**Comment by kylebradbury** [comment]
I'll update those labels.

**Comment by kylebradbury** [comment]
I've updated those figures (and remove mention of scalars so as not to muddy the waters). I think that takes care of this issue - closing; let me know if you'd like any other changes, of course.
