### ISSUE TITLE
Update materials on assigning into subsets

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#59]
I was teaching with you boot camp for social scientists this week and reddiscovered a pain point that I also ran into last semester, but clearly did not sufficiently correct in the instructional materials: students REALLY struggle with [] on the left side of the = when you're trying to sign into a subset of an array. Sub setting on the right side of the = where you're getting a subset was fine, assigning into a subset was was. 

Part of that is that R doesn't have a concept of views, which makes this a little bit more natural, but we had views initially, so or students may also struggle with it

**Comment by kylebradbury** [comment]
This is a great point - would a good place for a discussion of this be C2W2, 30_subsetting_vectors.ipynb?
