### ISSUE TITLE
broadcast reading visual typos

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#61]
<img width="823" alt="image" src="https://user-images.githubusercontent.com/9683693/191327377-fcb0baf5-08a2-40a1-b6fd-20865b2edcd7.png">

Output matrix wrong.

**Comment by kylebradbury** [comment]
Fixed this in [this commit](https://github.com/nickeubank/mids_coursera/commit/336d622aa2c1f3747ae191ee27f2477a69c5b560)

**Comment by kylebradbury** [comment]
I had to use the silly "?1" query separator to trick jupyter/github into recognizing that the Jupyter notebook had been updated... Just an FYI in case you see this here and there down the road.
