### ISSUE TITLE
Array headings

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#63]
One of my most thoughtful students (Heather Qiu) brought up a really good but subtle point: in our images about views and copies, we label the arrays with the names of the variables that point to them: 

![image](https://user-images.githubusercontent.com/9683693/192559689-e86458ed-f7f6-4057-afd6-861c06b86714.png)

While simplifying, it obscures the distinction between objects and variables, which _is_ super important to understand for things like modifying subsets / in place (where `my_array = my_array * 2` and `my_array[:] = my_array * 2` differ in precisely whether they're creating new objects). 

So I think we should update all our illustrations to make that distinction more explicit even if it adds more arrows.

More like these pics I stole: https://www.practicaldatascience.org/html/vars_v_objects.html

**Comment by kylebradbury** [comment]
This is an interesting point - thanks for mentioning it. I wonder if we could add in a short additional reading around this distinction may clarify this situation? Let me play around with some ideas of how we can convey this through the imagery and think through how and when would be best for stating that distinction (for example, D&G have the same setup, and probably the learners don't need to know that distinction in course 1). We may not need that distinction everywhere, but do need to make clear that concept especially around views/copies. I'll reflect on this...

**Comment by kylebradbury** [comment]
Drafted [this reading](https://github.com/nickeubank/mids_coursera/blob/main/class_2/week_3/13_objects_and_variables.ipynb) to address this variable/pointer relationship. Let me know if you think this addresses the issue sufficiently well - happy to edit further.

**Comment by nickeubank** [comment]
I think it's good! Only thing I'd suggest is to run it by drew and Genevieve for consistency, since they probably talk about this stuff some earlier.
