### ISSUE TITLE
need to run Grammarly against _everything_ for Course 2

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#67]
I have recently discovered the magic of Grammarly, and suffice to say it is not impressed by our (mostly my) proofreading skills. Typos abound, so we have to make sure that we proofread everything before it goes up.

- [x] Vectors (Week 2) @nickeubank 
- [x] Matrices  (Week 3) @nickeubank 
- [x] Matrix math (Week 4) @kylebradbury

**Comment by kylebradbury** [comment]
On it! Didn't know there was a Grammarly plugin for VS Code... trying it out now.

**Comment by nickeubank** [comment]
there is for latex and markdown, but doesn't work in notebooks. But if you put in browser, it WILL run on coursera when you're in an edit window.

**Comment by kylebradbury** [comment]
Done - will run it on any further tweaks made going forward as well.
