### ISSUE TITLE
Michael: Could you please update coursera version of...

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#69]
[this modifying subsets reading](https://github.com/nickeubank/mids_coursera/blob/main/class_2/week_2/35_modifying_subsets_of_vectors.ipynb) from class 2 week 2? 

The top half is substantially reworked to address #59.

@mvhudson-duke

**Comment by mvhudson-duke** [comment]
you got it!

**Comment by nickeubank** [comment]
Thanks!
