### ISSUE TITLE
Add visualization for assigning into a subset

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#70]
@kylebradbury here's the revised writeup I think could use a new image: https://github.com/nickeubank/mids_coursera/blob/main/class_2/week_2/35_modifying_subsets_of_vectors.ipynb

See the note about halfway down (a medium size header) where I think an image would be helpful!

**Comment by kylebradbury** [comment]
@nickeubank - take a peek at the two figures I've added to this reading when you get a chance and let me know if these work / if there are any changes you'd like!

**Comment by nickeubank** [comment]
perfect! Thank you, that's exactly what I was looking for!

**Comment by nickeubank** [comment]
Closing under the assumption that you have a note to update these in coursera.

**Comment by kylebradbury** [comment]
Yes - I've noted that update on our punch list! Thanks!
