### ISSUE TITLE
Add a graphic in the view copies reading? 

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#71]
I split the view copy reading into two parts and fleshed out the discussion of having square brackets on the left side of an assignment operator. I think it's low priority but it might be useful to have a graphic just above the start of the "Making a Copy" section in [this reading.](https://github.com/nickeubank/mids_coursera/blob/main/class_2/week_3/11_when_do_I_get_a_view.ipynb)

**Comment by nickeubank** [comment]
I think this is done, reopen if not.

**Comment by kylebradbury** [comment]
I've added a couple of images to this reading. Please let me know if you'd like them tweaked!
