### ISSUE TITLE
Explain jupyter interactive window

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#74]
So... guess we gotta Jupyter pretty early on!

**Comment by nickeubank** [comment]
Updated image so shift-enter opens interactive window: 
![image](https://user-images.githubusercontent.com/9683693/200199927-7fa13512-2a82-4cb6-9911-8ff13fcdc609.png)

**Comment by nickeubank** [comment]
@kylebradbury [this ok?](https://github.com/nickeubank/mids_coursera/blob/main/class_2/week_1/00_interactive_console.ipynb) Note sure what else to say...

**Comment by kylebradbury** [comment]
Looks great - fixed a small typo. Good-to-go from my perspective - closing the issue.
