### ISSUE TITLE
Script links

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#77]
[Class 1 intro](https://docs.google.com/document/d/1ljA6kgvQ8tXGyhDZYN0S-xBa1FW6klC5Cuy2a-Sa_fw/edit)
[Class 2 intro](https://docs.google.com/document/d/1lzGPj1fbJwDu7MLlj1c2bQxVSh_tmXzczNOe7xapnpo/edit?usp=sharing)

**Comment by nickeubank** [comment]
OK, added more to Course 1 and Course 2 intros. Maybe good? Not sure if we need more than that...

@mvhudson-duke could you let us know, especially with Course 2?

**Comment by kylebradbury** [comment]
All filmed, so closing
