### ISSUE TITLE
Update image reading on coursera 

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#78]
@mvhudson-duke Could I please ask you to update the Coursera reading on images [with the materials here?](https://github.com/nickeubank/mids_coursera/blob/main/class_2/week_3/25_images_as_matrices.ipynb)

**Comment by nickeubank** [comment]
@mvhudson-duke any chance we could do this this week or next? THANKS!

**Comment by mvhudson-duke** [comment]
Should be good to go! [Check it out here](https://www.coursera.org/teach/numpy-data-science/FiD87hWPEey8CQo63UjS5w/content/item/supplement/QztmC) and make sure everything looks right to you!

**Comment by kylebradbury** [comment]
@nickeubank - I assume that this was all set, so am closing the issue.
